### ISSUE TITLE
React Router does not work for permaweb apps

### ISSUE THREAD

**Issue by rosmcmahon** [chenraz/ArBounty#1]
this one is simple to fix. just swap out Router for HashRouter! 😃

example error:

![image](https://user-images.githubusercontent.com/1430130/154034720-a7c01f16-6e86-4fd0-8340-645d2c33212c.png)

the app's url should be in a subfolder with the txid as the name. eg. 
`xyz-subdomain-abc.arweave.net/abc-apptxid-123/newTender`

**Comment by chenraz** [comment]
Thank you very much for the tip.
This will be fixed in coming commits
